CityFunc.Web/CityFunc.Web/Models/Funcionario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CityFunc.Web.Models
{
    [Table("Funcionario")]
    public class Funcionario
    {
        [Key]
        [Required(ErrorMessage = "Id obrigatório")]
        [Display(Name = "ID")]
        public int Id { get; set; }

        [Required(ErrorMessage = "Favor informar Nome Completo.")]
        [Display(Name = "Nome Completo")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Favor informar Telefone.")]        
        [MinLength(10, ErrorMessage = "Mínimo 10 Caracteres")]
        [Display(Name = "Telefone")]
        public string Telefone { get; set; }

        [Required(ErrorMessage = "Favor informar CPF.")]        
        [MinLength(11, ErrorMessage = "Mínimo 11 Caracteres")]
        [Display(Name = "CPF")]
        public string CPF { get; set; }
        
        [Required(ErrorMessage = "Favor informar CEP.")]        
        [MinLength(8, ErrorMessage = "Mínimo 8 Caracteres")]
        [Display(Name = "CEP")]
        public string CEP { get; set; }

        [Required(ErrorMessage = "Favor informar Endereço.")]
        [Display(Name = "Endereço")]
        public string Endereco { get; set; }

        [Required(ErrorMessage = "Favor informar Numero.")]
        [Display(Name = "Número")]
        [MinLength(1, ErrorMessage = "Mínimo 1 Caracteres")]
        public string Numero { get; set; }

        [Display(Name = "Complemento")]
        public string Complemento { get; set; }

        [Required(ErrorMessage = "Favor informar Municipio.")]
        [Display(Name = "Município")]
        public string Municipio { get; set; }

        [Required(ErrorMessage = "Favor informar Estado.")]
        [StringLength(2, ErrorMessage = "Máximo 2 Caracteres")]
        [Display(Name = "Estado")]
        public string UF { get; set; }

        [Display(Name = "Foto")]
        public string Foto { get; set; }
    }
}

CityFunc.Web/CityFunc.Web/Controllers/FuncionariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using CityFunc.Web.Entity.Context;
using CityFunc.Web.Models;

namespace CityFunc.Web.Controllers
{
    public class FuncionariosController : Controller
    {
        private Context db = new Context();

        public ActionResult Index()
        {
            return View(db.Funcionario.ToList());
        }

        public PartialViewResult _partialSearch(string text)
        {
            if (text != null)
            {
                var searchList = db.Funcionario.Where(x => x.Nome.Contains(text.ToLower()) || x.UF.Contains(text.ToLower()) || x.Municipio.Contains(text.ToLower()) ).ToList();
                return PartialView(searchList);
            }
            else
            {
                var list = db.Funcionario.ToList();
                return PartialView(list);
            }
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Funcionario funcionario = db.Funcionario.Find(id);
            if (funcionario == null)
            {
                return HttpNotFound();
            }
            return View(funcionario);
        }

        public ActionResult Create()
        {
            ViewBag.ListaDeUF = db.Municipio.Select(x => x.UF).Distinct().ToList();
            ViewBag.ListaDeCidade = db.Municipio.Select(x => x.Nome).Distinct().ToList();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Funcionario funcionario, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string img = System.IO.Path.GetFileName(file.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("/Pictures"), img);
                    file.SaveAs(path);

                    funcionario.Foto = img;
                }
                else
                {
                    funcionario.Foto = "#";
                }

                var apenasDigitos = new Regex(@"[^\d]");

                funcionario.CPF = apenasDigitos.Replace(funcionario.CPF, "");
                funcionario.CEP = apenasDigitos.Replace(funcionario.CEP, "");
                funcionario.Telefone = apenasDigitos.Replace(funcionario.Telefone, "");

                db.Funcionario.Add(funcionario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(funcionario);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.ListaDeUF = db.Municipio.Select(x => x.UF).Distinct().ToList();
            ViewBag.ListaDeCidade = db.Municipio.Select(x => x.Nome).Distinct().ToList();

            Funcionario funcionario = db.Funcionario.Find(id);
            if (funcionario == null)
            {
                return HttpNotFound();
            }
            return View(funcionario);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Funcionario funcionario, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string img = System.IO.Path.GetFileName(file.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("/Pictures"), img);
                    file.SaveAs(path);

                    funcionario.Foto = img;
                }
                else
                {
                    funcionario.Foto = "#";
                }

                var apenasDigitos = new Regex(@"[^\d]");

                funcionario.CPF = apenasDigitos.Replace(funcionario.CPF, "");
                funcionario.CEP = apenasDigitos.Replace(funcionario.CEP, "");
                funcionario.Telefone = apenasDigitos.Replace(funcionario.Telefone, "");

                db.Entry(funcionario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(funcionario);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Funcionario funcionario = db.Funcionario.Find(id);
            if (funcionario == null)
            {
                return HttpNotFound();
            }
            return View(funcionario);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Funcionario funcionario = db.Funcionario.Find(id);
            db.Funcionario.Remove(funcionario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CityFunc.Web/CityFunc.Web/Views/Funcionarios/Create.cshtml
@model CityFunc.Web.Models.Funcionario

    @using (Html.BeginForm("Create", "Funcionarios", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Funcionário</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">  
                <div class="row">
                    <div class="col-md-8">
                        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control col", @placeholder = "Ex: Pedro" } })
                        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control col", @placeholder = "Ex: 526.751.520-00" } })
                        @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    
    
            <div class="form-group">
                <div class="row">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.CEP, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @class = "form-control col", @placeholder = "Ex: 99950-520" } })
                        @Html.ValidationMessageFor(model => model.CEP, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-5">
                        @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control col", @placeholder = "Ex: Rua Joana" } })
                        @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-1">
                        @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control col", @placeholder = "Ex: 110" } })
                        @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-1">
                        @Html.LabelFor(model => model.UF, htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownListFor(model => model.UF, new SelectList(ViewBag.ListaDeUF), new { @class = "form-control col" } )
                        @Html.ValidationMessageFor(model => model.UF, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-3">                        
                        @Html.LabelFor(model => model.Municipio, htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownListFor(model => model.Municipio, new SelectList(ViewBag.ListaDeCidade), new { @class = "form-control col" })
                        @Html.ValidationMessageFor(model => model.Municipio, "", new { @class = "text-danger" })
                    </div>                    
                </div>                               
            </div>
    
            <div class="form-group">
                <div class="row">
                    <div class="col-md-3">
                        @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control col" } })
                        @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-3">
                        @Html.LabelFor(model => model.Complemento, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Complemento, new { htmlAttributes = new { @class = "form-control col" } })
                        @Html.ValidationMessageFor(model => model.Complemento, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>  
            
            <div class="form-group">
                <div class="row">
                    <div class="col-md-12">                        
                        <label for="file">Foto</label>
                        <input type="file" name="file" id="file" class="form-control-file" />
                    </div>
                </div>
            </div>
   
            <div class="form-group">
                <div class="row">
                    <div class="col-md-10">
                        <br />
                        <input type="submit" value="Cadastrar" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    }

CityFunc.Web/CityFunc.Web/Views/Funcionarios/Delete.cshtml
@model CityFunc.Web.Models.Funcionario

<h3>Tem certeza que quer deletar este Funcionario?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.CPF)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.CEP)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.CEP)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Endereco)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Numero)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Numero)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Complemento)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Complemento)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Municipio)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Municipio)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.UF)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.UF)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>
    
    </dl>
    
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
    
        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class="btn btn-danger" />
        </div>
    }
</div>

CityFunc.Web/CityFunc.Web/Views/Funcionarios/Details.cshtml
@model CityFunc.Web.Models.Funcionario


    <div>
        <h4>Funcionário</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nome)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Nome)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Telefone)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Telefone)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CPF)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CPF)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CEP)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CEP)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Endereco)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Endereco)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Numero)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Numero)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Complemento)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Complemento)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Municipio)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Municipio)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.UF)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.UF)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Foto)
            </dt>
    
            <dd>
                <img src="~/Pictures/@Html.DisplayFor(model => model.Foto)" alt="Foto" style="max-height: 60px" />
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new {@class = "btn btn-primary" })        
    </p>

CityFunc.Web/CityFunc.Web/Views/Funcionarios/Edit.cshtml
@model CityFunc.Web.Models.Funcionario

    @using (Html.BeginForm("Edit", "Funcionarios", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Funcionário</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div class="row">
            <div class="col-md-8">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control col", @placeholder = "Ex: Pedro" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control col", @placeholder = "Ex: 526.751.520-00" } })
                @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>


    <div class="form-group">
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(model => model.CEP, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @class = "form-control col", @placeholder = "Ex: 99950-520" } })
                @Html.ValidationMessageFor(model => model.CEP, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-5">
                @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control col", @placeholder = "Ex: Rua Joana" } })
                @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-1">
                @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control col", @placeholder = "Ex: 110" } })
                @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-1">
                @Html.LabelFor(model => model.UF, htmlAttributes: new { @class = "control-label" })
                @Html.DropDownListFor(model => model.UF, new SelectList(ViewBag.ListaDeUF), new { @class = "form-control col" })
                @Html.ValidationMessageFor(model => model.UF, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => model.Municipio, htmlAttributes: new { @class = "control-label" })
                @Html.DropDownListFor(model => model.Municipio, new SelectList(ViewBag.ListaDeCidade), new { @class = "form-control col" })
                @Html.ValidationMessageFor(model => model.Municipio, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control col" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => model.Complemento, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Complemento, new { htmlAttributes = new { @class = "form-control col" } })
                @Html.ValidationMessageFor(model => model.Complemento, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-md-12">
                <label for="file">Foto</label>
                <input type="file" name="file" id="file" class="form-control-file" />
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-md-10">
                <br />
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </div>
    </div>
</div>
    }

CityFunc.Web/CityFunc.Web/Views/Funcionarios/Index.cshtml
@model IEnumerable<CityFunc.Web.Models.Funcionario>

<div class="row">
    <div class="col-md-12" align="left">
        @Html.ActionLink("Cadastrar", "Create", null, new { @class = "btn btn-primary" })
        <br />
    </div>
    <div class="col-md-12">
        <br />
        @{Html.RenderAction("_partialSearch");}
    </div>
</div>

CityFunc.Web/CityFunc.Web/Views/Funcionarios/_partialSearch.cshtml
@model IEnumerable<CityFunc.Web.Models.Funcionario>


@using (Html.BeginForm())
{
    <div class="form-inline">
        <input name="text" id="text" class="form-control col mr-sm-2" type="search" placeholder="Ex: Pedro Henrique, Porto Alegre, RS">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></button>
    </div>
}

@if (Model.Any())
{
    <br />
    <table class="table table-bordered table-hover text-center table-sm">
        <thead>
            <tr>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Telefone)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.CPF)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.CEP)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Endereco)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Numero)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Complemento)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Municipio)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.UF)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Foto)
                </th>
                <th scope="col"></th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
        <tbody>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Telefone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CPF)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CEP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Endereco)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Numero)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Complemento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Municipio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UF)
                </td>
                <td>
                    <img src="~/Pictures/@Html.DisplayFor(modelItem => item.Foto)" alt="Foto" style="max-height: 60px" />
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Detalhes", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Deletar", "Delete", new { id = item.Id })
                </td>
            </tr>
        </tbody>
        }
    </table>
}
else
{
    <br />
    <div class="alert alert-warning" role="alert">Nenhum Registro Encontrado.</div>
}